package com.solegendary.reignofnether.registrars;

import com.solegendary.reignofnether.ReignOfNether;
import com.solegendary.reignofnether.ability.AbilityClientboundPacket;
import com.solegendary.reignofnether.ability.AbilityServerboundPacket;
import com.solegendary.reignofnether.ability.BuildingAbilityClientboundPacket;
import com.solegendary.reignofnether.ability.BuildingAbilityServerboundPacket;
import com.solegendary.reignofnether.alliance.*;
import com.solegendary.reignofnether.attackwarnings.AttackWarningClientboundPacket;
import com.solegendary.reignofnether.building.*;
import com.solegendary.reignofnether.building.custombuilding.CustomBuildingClientboundPacket;
import com.solegendary.reignofnether.building.custombuilding.CustomBuildingServerboundPacket;
import com.solegendary.reignofnether.config.ClientboundSyncResourceCostPacket;
import com.solegendary.reignofnether.debug.RtsDebugChunksClientboundPacket;
import com.solegendary.reignofnether.debug.RtsDebugStatsClientboundPacket;
import com.solegendary.reignofnether.fogofwar.*;
import com.solegendary.reignofnether.gamemode.GameModeClientboundPacket;
import com.solegendary.reignofnether.gamemode.GameModeServerboundPacket;
import com.solegendary.reignofnether.gamerules.GameruleClientboundPacket;
import com.solegendary.reignofnether.gamerules.GameruleServerboundPacket;
import com.solegendary.reignofnether.guiscreen.TopdownGuiServerboundPacket;
import com.solegendary.reignofnether.hero.FallenHeroClientboundPacket;
import com.solegendary.reignofnether.hero.HeroClientboundPacket;
import com.solegendary.reignofnether.hero.HeroServerboundPacket;
import com.solegendary.reignofnether.hud.HudClientboundPacket;
import com.solegendary.reignofnether.hud.custombutton.CustomButtonActionServerboundPacket;
import com.solegendary.reignofnether.hud.custombutton.CustomButtonClientboundPacket;
import com.solegendary.reignofnether.items.ItemClientboundPacket;
import com.solegendary.reignofnether.items.ItemServerboundPacket;
import com.solegendary.reignofnether.items.ItemShopClientboundPacket;
import com.solegendary.reignofnether.minimap.MapMarkerClientboundPacket;
import com.solegendary.reignofnether.minimap.MapMarkerServerboundPacket;
import com.solegendary.reignofnether.orthoview.CameraClientboundPacket;
import com.solegendary.reignofnether.orthoview.CameraFadeClientboundPacket;
import com.solegendary.reignofnether.player.MatchStatsClientboundPacket;
import com.solegendary.reignofnether.player.PlayerClientboundPacket;
import com.solegendary.reignofnether.player.PlayerServerboundPacket;
import com.solegendary.reignofnether.research.ResearchClientboundPacket;
import com.solegendary.reignofnether.research.ResearchServerboundPacket;
import com.solegendary.reignofnether.resources.ResourcesClientboundPacket;
import com.solegendary.reignofnether.resources.ResourcesServerboundPacket;
import com.solegendary.reignofnether.rtsmap.RTSMapInfoClientboundPacket;
import com.solegendary.reignofnether.rtsmap.RTSMapInfoServerboundPacket;
import com.solegendary.reignofnether.sandbox.SandboxServerboundPacket;
import com.solegendary.reignofnether.scenario.ScenarioClientboundPacket;
import com.solegendary.reignofnether.scenario.ScenarioServerboundPacket;
import com.solegendary.reignofnether.sounds.SoundClientboundPacket;
import com.solegendary.reignofnether.startpos.StartPosClientboundPacket;
import com.solegendary.reignofnether.startpos.StartPosServerboundPacket;
import com.solegendary.reignofnether.survival.SurvivalClientboundPacket;
import com.solegendary.reignofnether.survival.SurvivalServerboundPacket;
import com.solegendary.reignofnether.tutorial.TutorialClientboundPacket;
import com.solegendary.reignofnether.tutorial.TutorialServerboundPacket;
import com.solegendary.reignofnether.unit.packets.*;
import net.neoforged.fml.ModContainer;
import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent;
import net.neoforged.neoforge.network.registration.PayloadRegistrar;

// Registers all C2S/S2C payloads with NeoForge's payload system.
public final class PacketHandler {

    private PacketHandler() { }

    public static void register(final RegisterPayloadHandlersEvent event) {
        final PayloadRegistrar registrar = event.registrar("1");
        registrar.playToServer(TopdownGuiServerboundPacket.TYPE, TopdownGuiServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(UnitActionServerboundPacket.TYPE, UnitActionServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(BeaconSyncClientboundPacket.TYPE, BeaconSyncClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(UnitConvertClientboundPacket.TYPE, UnitConvertClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(UnitSyncClientboundPacket.TYPE, UnitSyncClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(UnitSyncWorkerClientBoundPacket.TYPE, UnitSyncWorkerClientBoundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(UnitSyncAbilityClientboundPacket.TYPE, UnitSyncAbilityClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(UnitSyncServerboundPacket.TYPE, UnitSyncServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(UnitAnimationClientboundPacket.TYPE, UnitAnimationClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(UnitPathClientboundPacket.TYPE, UnitPathClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(RtsDebugStatsClientboundPacket.TYPE, RtsDebugStatsClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(RtsDebugChunksClientboundPacket.TYPE, RtsDebugChunksClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(UnitIdleWorkerClientBoundPacket.TYPE, UnitIdleWorkerClientBoundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(ResearchClientboundPacket.TYPE, ResearchClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(ResearchServerboundPacket.TYPE, ResearchServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(PlayerServerboundPacket.TYPE, PlayerServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(PlayerClientboundPacket.TYPE, PlayerClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(FogOfWarClientboundPacket.TYPE, FogOfWarClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(FogChunksClientboundPacket.TYPE, FogChunksClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(FogOfWarServerboundPacket.TYPE, FogOfWarServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(FrozenChunkClientboundPacket.TYPE, FrozenChunkClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(BuildingServerboundPacket.TYPE, BuildingServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(BuildingClientboundPacket.TYPE, BuildingClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(BuildingProductionServerboundPacket.TYPE, BuildingProductionServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(BuildingProductionClientboundPacket.TYPE, BuildingProductionClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(ResourcesClientboundPacket.TYPE, ResourcesClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(ResourcesServerboundPacket.TYPE, ResourcesServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(AbilityClientboundPacket.TYPE, AbilityClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(AbilityServerboundPacket.TYPE, AbilityServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(BuildingAbilityServerboundPacket.TYPE, BuildingAbilityServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(BuildingAbilityClientboundPacket.TYPE, BuildingAbilityClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(AttackWarningClientboundPacket.TYPE, AttackWarningClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(SoundClientboundPacket.TYPE, SoundClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(TutorialClientboundPacket.TYPE, TutorialClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(TutorialServerboundPacket.TYPE, TutorialServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(AllianceClientboundPacket.TYPE, AllianceClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(AllianceServerboundPacket.TYPE, AllianceServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(GameModeServerboundPacket.TYPE, GameModeServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(GameModeClientboundPacket.TYPE, GameModeClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(SurvivalServerboundPacket.TYPE, SurvivalServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(SurvivalClientboundPacket.TYPE, SurvivalClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(ClientboundSyncResourceCostPacket.TYPE, ClientboundSyncResourceCostPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(SandboxServerboundPacket.TYPE, SandboxServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(GameruleServerboundPacket.TYPE, GameruleServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(GameruleClientboundPacket.TYPE, GameruleClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(StartPosServerboundPacket.TYPE, StartPosServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(StartPosClientboundPacket.TYPE, StartPosClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(HeroClientboundPacket.TYPE, HeroClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(HeroServerboundPacket.TYPE, HeroServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(FallenHeroClientboundPacket.TYPE, FallenHeroClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(CustomBuildingClientboundPacket.TYPE, CustomBuildingClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(CustomBuildingServerboundPacket.TYPE, CustomBuildingServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(UnitSyncMobEffectsClientboundPacket.TYPE, UnitSyncMobEffectsClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(MapMarkerServerboundPacket.TYPE, MapMarkerServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(MapMarkerClientboundPacket.TYPE, MapMarkerClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(ScenarioServerboundPacket.TYPE, ScenarioServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(ScenarioClientboundPacket.TYPE, ScenarioClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(MatchStatsClientboundPacket.TYPE, MatchStatsClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(RTSMapInfoClientboundPacket.TYPE, RTSMapInfoClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(RTSMapInfoServerboundPacket.TYPE, RTSMapInfoServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(PlayerChunksClientboundPacket.TYPE, PlayerChunksClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(HudClientboundPacket.TYPE, HudClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(CameraClientboundPacket.TYPE, CameraClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(CameraFadeClientboundPacket.TYPE, CameraFadeClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(FogNeutralUnitClientboundPacket.TYPE, FogNeutralUnitClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(FogBuildingClientboundPacket.TYPE, FogBuildingClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(CustomButtonActionServerboundPacket.TYPE, CustomButtonActionServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(CustomButtonClientboundPacket.TYPE, CustomButtonClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToServer(ItemServerboundPacket.TYPE, ItemServerboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(ItemClientboundPacket.TYPE, ItemClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
        registrar.playToClient(ItemShopClientboundPacket.TYPE, ItemShopClientboundPacket.STREAM_CODEC, (payload, ctx) -> payload.handle(ctx));
    }
}
